- name: Play1
  hosts: all
  tasks:
    - name: Ping
      ping: 
    
- name: Play2
  hosts: all
  tasks:
    - name: Create an empty file in remote node
      file:
        path: /tmp/demo
        state: touch

