- name: Install web server
  hosts: all
  tasks:
    - name: Install Web Server
      package:
        name: httpd
        state: present
 
    - name: Start httpd
      package:
        name: httpd
        state: started