- name: print variable using var-prompt
  hosts: all
  vars_prompt:
    - prompt: Enter URL
      name: URL
      private: no
  tasks:
    - name: print var-prompt
      debug:
        msg: "URL = {{URL}}"


