- name: print variable using var-prompt
  hosts: all
  vars_prompt:

    - name: URL
      prompt: Enter URL
      private: no

  tasks:
    - name: print var-prompt
      debug:
        msg: "URL = {{URL}}"