- name: Print gather fact variables
  hosts: all
  tasks:
    - name: Print ansible_machine
      debug:
        msg: "Python version - {{ansible_python_version}}"

    - name: Print facts from node1
      debug:
        msg: "{{ansible_local.demo.URL}}"