- name: vars from task and play
  hosts: all
  #vars:
   # URL: "play.google.com"
  tasks:
    - name: print from task
      debug:
        msg: "URL: {{URL}}"
      #vars:
       # URL: "tasks.google.com"
