- name: Demo on when condition
  hosts: all
  tasks:
    - name: Check rpm command is there or not
      command: which rpm
      when: ansible_distribution == "Centos"

    - name: check dpkg cmd is there or not
      command: which dpkg
      when: ansible_distribution == "Ubuntu"