- name: Demo on ignore_errors
  hosts: all
  tasks:
    - name: check dpkg cmd
      command: which rpm
      register: out

    - name: find kernel rpm version
      shell: dpkg --list | grep kernel
      when: out.rc == 0