- name: Demo on loops
  hosts: all
  gather_facts: no
  tasks:
    - name: Print Hello
      debug:
        msg: "Hello, {{item}}"
      loop:
        - Ram
        - Aam
        - Sam
        - Pam

    - name: Print group of items
      debug:
        msg: "{{item}}"
      loop:
        - ["One", "Two"]
        - ["Smit", "Vijay"]

