- name: Demo on Print load
  hosts: all
  tasks:
    - name: Print avg load
      command: uptime
      register: out

    - name: Fetch the load value
      set_fact:
        LOAD: "{{out.stdout.split()[-3].split('.')[0]}}"

    - name: send an email
      command: curl ....
      when: LOAD > 5