- name: Demo on Print load
  hosts: all
  tasks:
    - name: Print avg load
      command: uptime
      register: out

    - name: Fetch the load value
      debug:
        msg: "{{out.stdout | split}}"