- name: Install Java
  package:
    name: java
    state: present

- name: Create Application USer
  user:
    name: {{APP_USER}}

- name: download latest verson of tomcat
  unarchive:
    src: {{TOMCAT_URL}}
    dest: {{APP_HOME}}
    remote_src: yes