- name: Install Java
  package:
    name: java
    state: present

- name: Create Application User
  user:
    name: "{{APP_USER}}"
  

- name: download latest verson of tomcat
  unarchive:
    src: "{{TOMCAT_URL}}"
    dest: "{{APP_HOME}}"
    remote_src: yes
  become_user: "{{APP_USER}}"
  notify: restart tomcat

- name: download student app
  get_url:
    url: "{{WAR_URL}}"
    dest: "{{TOMCAT_HOME}}/webapps/student.war"
  become_user: "{{APP_USER}}"
  notify: restart tomcat

- name: download jdbc driver
  get_url:
    url: "{{JAR_URL}}"
    dest: "{{TOMCAT_HOME}}/lib/mysql-connector.jar"
  become_user: "{{APP_USER}}"
  notify: restart tomcat

- name: Copy context.xml file 
  template:
    src: context.xml
    dest: "{{TOMCAT_HOME}}/conf/context.xml"
  become_user: "{{APP_USER}}"
  notify: Restart Tomcat


- name: Download tomcat init script
  get_url:
    url: "{{TOMCAT_INIT_SCRIPT}}"
    dest: /etc/init.d/tomcat
    mode: '0755'
    notify: daemon reload

- name: start tomcat service
  service:
    name: tomcat
    state: started
    enabled: yes

